# Generated by Django 6.0.4 on 2026-04-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='initial_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Розмінний фонд'),
        ),
    ]
