# Generated by Django 6.0.4 on 2026-04-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComboMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dishes', models.ManyToManyField(related_name='combos', to='menu.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combos', models.ManyToManyField(blank=True, to='menu.combomeal')),
                ('dishes', models.ManyToManyField(blank=True, to='menu.dish')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='canteen.shift')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='menu.dish')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='canteen.shift')),
            ],
            options={
                'unique_together': {('shift', 'dish')},
            },
        ),
    ]
