# Generated by Django 6.0.4 on 2026-04-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='weight_info',
            field=models.CharField(blank=True, help_text='Наприклад: 300г, 1шт', max_length=50),
        ),
    ]
