# Generated by Django 6.0.4 on 2026-04-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_weight_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
