# Generated by Django 6.0.4 on 2026-04-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_shift_initial_cash'),
        ('menu', '0004_dish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishments', to='canteen.shift')),
            ],
        ),
    ]
