# Generated by Django 6.0.4 on 2026-04-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачен'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='pending', max_length=15)),
                ('order_type', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн (Касса)')], default='offline', max_length=10)),
                ('payment_method', models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные'), ('voucher', 'Ваучер (Талон)')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_fixed', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
