# Generated by Django 6.0.4 on 2026-04-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Час отримання (Time-slot)'),
        ),
    ]
